version: "3"
services:
  web:
    container_name: web-app
    build: 
      dockerfile: Dockerfile
      context: MvcApp
    ports:
      - "8008:80"
    environment:
      ConnectionStrings__ProductsContext: "Server=db;Database=ProductsContext;User=sa;Password=@Aa123456;"
    depends_on:
      - db

  db:
    container_name: mssql-db
    image: "mcr.microsoft.com/azure-sql-edge:latest" #"microsoft/mssql-server-linux"
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "@Aa123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"